In [3]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
from scipy import stats

In [8]:
df=pd.read_csv("US_Accidents_May19.csv")
df.head()

ID    Source  TMC  Severity     Start_Time        End_Time  Start_Lat  \
0  A-1  MapQuest  201         3  2/8/2016 5:46  2/8/2016 11:00  39.865147   
1  A-2  MapQuest  201         2  2/8/2016 6:07   2/8/2016 6:37  39.928059   
2  A-3  MapQuest  201         2  2/8/2016 6:49   2/8/2016 7:19  39.063148   
3  A-4  MapQuest  201         3  2/8/2016 7:23   2/8/2016 7:53  39.747753   
4  A-5  MapQuest  201         2  2/8/2016 7:39   2/8/2016 8:09  39.627781   

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...   
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...   
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...   
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...   
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...   

   ...  Roundabout Station   Stop Traffic_Calming Traffic_Signal Turning_Loop  \
0  ...       False   False  False           False          False        False   
1  ...       False   False  False           False          False        False   
2  ...       False   False  False           False           True        False   
3  ...       False   False  False           False          False        False   
4  ...       False   False  False           False           True        False   

  Sunrise_Sunset Civil_Twilight Nautical_Twilight Astronomical_Twilight  
0          Night          Night             Night                 Night  
1          Night          Night             Night                   Day  
2          Night          Night               Day                   Day  
3          Night            Day               Day                   Day  
4            Day            Day               Day                   Day  

[5 rows x 47 columns]

In [6]:
m = df['Severity'].mean()
df['Severity'].fillna(m, inplace=True)
m = df['Start_Lat'].mean()
df['Start_Lat'].fillna(m, inplace=True)
m = df['Start_Lng'].mean()
df['Start_Lng'].fillna(m, inplace=True)
m = df['Distance(mi)'].mean()
df['Distance(mi)'].fillna(m, inplace=True)
m = df['Temperature(F)'].mean()
df['Temperature(F)'].fillna(m, inplace=True)
m = df['Wind_Chill(F)'].mean()
df['Wind_Chill(F)'].fillna(m, inplace=True)
m = df['Humidity(%)'].mean()
df['Humidity(%)'].fillna(m, inplace=True)
m = df['Pressure(in)'].mean()
df['Pressure(in)'].fillna(m, inplace=True)
m = df['Visibility(mi)'].mean()
df['Visibility(mi)'].fillna(m, inplace=True)
m = df['Wind_Speed(mph)'].mean()
df['Wind_Speed(mph)'].fillna(m, inplace=True)
m = df['Precipitation(in)'].mean()
df['Precipitation(in)'].fillna(m, inplace=True)

In [7]:
df._get_numeric_data()

TMC  Severity  Start_Lat   Start_Lng  Distance(mi)   Number  \
0     201         3  39.865147  -84.058723          0.01      NaN   
1     201         2  39.928059  -82.831184          0.01   2584.0   
2     201         2  39.063148  -84.032608          0.01      NaN   
3     201         3  39.747753  -84.205582          0.01      NaN   
4     201         2  39.627781  -84.188354          0.01      NaN   
5     201         3  40.100590  -82.925194          0.01      NaN   
6     201         2  39.758274  -84.230507          0.00    376.0   
7     201         3  39.770382  -84.194901          0.01      NaN   
8     201         2  39.778061  -84.172005          0.00     99.0   
9     201         3  40.100590  -82.925194          0.01      NaN   
10    201         3  39.952812  -83.119293          0.01      NaN   
11    241         3  39.932709  -82.830910          0.01      NaN   
12    201         2  39.737633  -84.149933          0.00     99.0   
13    201         2  39.790760  -84.241547          0.01   3198.0   
14    201         2  39.972038  -82.913521          0.01   3280.0   
15    201         2  39.745888  -84.170410          0.01    100.0   
16    201         2  39.748329  -84.224007          0.01      NaN   
17    201         2  39.752174  -84.239952          0.00   3001.0   
18    201         2  39.740669  -84.184135          0.01    440.0   
19    201         2  39.790703  -84.244461          0.01   3499.0   
20    201         2  40.052509  -82.882332          0.00    193.0   
21    201         2  39.773346  -84.224686          0.00   1391.0   
22    201         2  39.628288  -84.226151          0.01      NaN   
23    201         3  40.023487  -82.994888          0.01      NaN   
24    201         2  39.761379  -84.259216          0.01   4401.0   
25    201         2  40.158024  -82.641762          1.32   7849.0   
26    201         2  39.733219  -84.159653          0.00   1240.0   
27    201         2  39.775303  -84.200523          0.00      1.0   
28    201         2  39.789322  -84.239105          0.01   2198.0   
29    201         2  39.758720  -84.183762          0.00    500.0   
...   ...       ...        ...         ...           ...      ...   
9970  201         2  38.298931 -122.127220          0.01   5158.0   
9971  201         2  38.017372 -121.095589          0.01  18001.0   
9972  201         3  37.425724 -121.916618          0.01      NaN   
9973  201         3  37.719204 -121.660400          0.01      NaN   
9974  201         3  37.740494 -121.586182          0.01      NaN   
9975  201         3  39.202686 -120.809448          0.01      NaN   
9976  201         2  38.743801 -121.223297          0.00   4199.0   
9977  201         3  37.737553 -122.140717          0.01      NaN   
9978  201         2  37.901688 -121.467857          0.01  12115.0   
9979  201         2  37.609432 -120.993591          0.01    100.0   
9980  201         3  38.641464 -121.462387          0.01      NaN   
9981  241         3  37.923428 -122.359985          0.01      NaN   
9982  201         2  37.468502 -122.154770          0.01      NaN   
9983  241         2  36.756168 -121.665146          0.01    651.0   
9984  201         2  38.263973 -122.727852          0.01   5541.0   
9985  201         2  38.937988 -121.144455          0.01   8999.0   
9986  201         3  37.900543 -121.284927          0.01      NaN   
9987  201         3  37.842594 -122.297600          0.01      NaN   
9988  201         3  37.588799 -121.870750          3.54      NaN   
9989  201         2  37.241005 -121.797180          0.01      NaN   
9990  201         2  38.456692 -121.410385          0.01      NaN   
9991  201         2  38.245728 -122.625511          0.01      NaN   
9992  201         3  37.564606 -121.902275          0.01      NaN   
9993  201         3  38.744102 -121.270569          0.01      NaN   
9994  201         2  37.066490 -121.219147          0.01      NaN   
9995  201         2  38.701267 -121.077751          0.00   3108.0   
9996

In [9]:
q=['Severity','Start_Lat','Start_Lng','Distance(mi)','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']
q

['Severity',
 'Start_Lat',
 'Start_Lng',
 'Distance(mi)',
 'Temperature(F)',
 'Wind_Chill(F)',
 'Humidity(%)',
 'Pressure(in)',
 'Visibility(mi)',
 'Wind_Speed(mph)',
 'Precipitation(in)']

In [10]:
q=df[['Severity','Start_Lat','Start_Lng','Distance(mi)','Temperature(F)','Wind_Chill(F)','Humidity(%)','Pressure(in)','Visibility(mi)','Wind_Speed(mph)','Precipitation(in)']]
q

Severity  Start_Lat   Start_Lng  Distance(mi)  Temperature(F)  \
0            3  39.865147  -84.058723          0.01            36.9   
1            2  39.928059  -82.831184          0.01            37.9   
2            2  39.063148  -84.032608          0.01            36.0   
3            3  39.747753  -84.205582          0.01            35.1   
4            2  39.627781  -84.188354          0.01            36.0   
5            3  40.100590  -82.925194          0.01            37.9   
6            2  39.758274  -84.230507          0.00            34.0   
7            3  39.770382  -84.194901          0.01            34.0   
8            2  39.778061  -84.172005          0.00            33.3   
9            3  40.100590  -82.925194          0.01            37.4   
10           3  39.952812  -83.119293          0.01            35.6   
11           3  39.932709  -82.830910          0.01            37.4   
12           2  39.737633  -84.149933          0.00            33.8   
13           2  39.790760  -84.241547          0.01            36.0   
14           2  39.972038  -82.913521          0.01            37.4   
15           2  39.745888  -84.170410          0.01            33.8   
16           2  39.748329  -84.224007          0.01            35.6   
17           2  39.752174  -84.239952          0.00            36.0   
18           2  39.740669  -84.184135          0.01            37.4   
19           2  39.790703  -84.244461          0.01            36.0   
20           2  40.052509  -82.882332          0.00            33.8   
21           2  39.773346  -84.224686          0.00            36.0   
22           2  39.628288  -84.226151          0.01            35.1   
23           3  40.023487  -82.994888          0.01            37.0   
24           2  39.761379  -84.259216          0.01            37.9   
25           2  40.158024  -82.641762          1.32            37.9   
26           2  39.733219  -84.159653          0.00            36.0   
27           2  39.775303  -84.200523          0.00            39.9   
28           2  39.789322  -84.239105          0.01            39.9   
29           2  39.758720  -84.183762          0.00            39.2   
...        ...        ...         ...           ...             ...   
9970         2  38.298931 -122.127220          0.01            51.1   
9971         2  38.017372 -121.095589          0.01            48.0   
9972         3  37.425724 -121.916618          0.01            52.0   
9973         3  37.719204 -121.660400          0.01            45.0   
9974         3  37.740494 -121.586182          0.01            45.0   
9975         3  39.202686 -120.809448          0.01            34.0   
9976         2  38.743801 -121.223297          0.00            46.4   
9977         3  37.737553 -122.140717          0.01            48.0   
9978         2  37.901688 -121.467857          0.01            48.0   
9979         2  37.609432 -120.993591          0.01            50.0   
9980         3  38.641464 -121.462387          0.01            46.4   
9981         3  37.923428 -122.359985          0.01            46.0   
9982         2  37.468502 -122.154770          0.01            50.0   
9983         2  36.756168 -121.665146          0.01            53.1   
9984         2  38.263973 -122.727852          0.01            46.4   
9985         2  38.937988 -121.144455          0.01            42.8   
9986         3  37.900543 -121.284927          0.01            48.0   
9987         3  37.842594 -122.297600          0.01            48.9   
9988         3  37.588799 -121.870750          3.54            43.0   
9989         2  37.241005 -121.797180          0.01            51.8   
9990         2  38.456692 -121.410385          0.01            46.0   
9991         2  38.245728 -122.625511          0.01            44.6   
9992         3  37.564606 -121.902275          0.01            43.0   
9993         3  38.744102 -121.270569          0.01            42.8   
9994         2  37.066490 -121

In [19]:
q.to_csv(r'F:\Abhishek\3rd sem\Introduction to data science\numeric.csv',index=False)

In [13]:
df.shape

(10000, 47)

In [11]:
q

Severity  Start_Lat   Start_Lng  Distance(mi)  Temperature(F)  \
0            3  39.865147  -84.058723          0.01            36.9   
1            2  39.928059  -82.831184          0.01            37.9   
2            2  39.063148  -84.032608          0.01            36.0   
3            3  39.747753  -84.205582          0.01            35.1   
4            2  39.627781  -84.188354          0.01            36.0   
5            3  40.100590  -82.925194          0.01            37.9   
6            2  39.758274  -84.230507          0.00            34.0   
7            3  39.770382  -84.194901          0.01            34.0   
8            2  39.778061  -84.172005          0.00            33.3   
9            3  40.100590  -82.925194          0.01            37.4   
10           3  39.952812  -83.119293          0.01            35.6   
11           3  39.932709  -82.830910          0.01            37.4   
12           2  39.737633  -84.149933          0.00            33.8   
13           2  39.790760  -84.241547          0.01            36.0   
14           2  39.972038  -82.913521          0.01            37.4   
15           2  39.745888  -84.170410          0.01            33.8   
16           2  39.748329  -84.224007          0.01            35.6   
17           2  39.752174  -84.239952          0.00            36.0   
18           2  39.740669  -84.184135          0.01            37.4   
19           2  39.790703  -84.244461          0.01            36.0   
20           2  40.052509  -82.882332          0.00            33.8   
21           2  39.773346  -84.224686          0.00            36.0   
22           2  39.628288  -84.226151          0.01            35.1   
23           3  40.023487  -82.994888          0.01            37.0   
24           2  39.761379  -84.259216          0.01            37.9   
25           2  40.158024  -82.641762          1.32            37.9   
26           2  39.733219  -84.159653          0.00            36.0   
27           2  39.775303  -84.200523          0.00            39.9   
28           2  39.789322  -84.239105          0.01            39.9   
29           2  39.758720  -84.183762          0.00            39.2   
...        ...        ...         ...           ...             ...   
9970         2  38.298931 -122.127220          0.01            51.1   
9971         2  38.017372 -121.095589          0.01            48.0   
9972         3  37.425724 -121.916618          0.01            52.0   
9973         3  37.719204 -121.660400          0.01            45.0   
9974         3  37.740494 -121.586182          0.01            45.0   
9975         3  39.202686 -120.809448          0.01            34.0   
9976         2  38.743801 -121.223297          0.00            46.4   
9977         3  37.737553 -122.140717          0.01            48.0   
9978         2  37.901688 -121.467857          0.01            48.0   
9979         2  37.609432 -120.993591          0.01            50.0   
9980         3  38.641464 -121.462387          0.01            46.4   
9981         3  37.923428 -122.359985          0.01            46.0   
9982         2  37.468502 -122.154770          0.01            50.0   
9983         2  36.756168 -121.665146          0.01            53.1   
9984         2  38.263973 -122.727852          0.01            46.4   
9985         2  38.937988 -121.144455          0.01            42.8   
9986         3  37.900543 -121.284927          0.01            48.0   
9987         3  37.842594 -122.297600          0.01            48.9   
9988         3  37.588799 -121.870750          3.54            43.0   
9989         2  37.241005 -121.797180          0.01            51.8   
9990         2  38.456692 -121.410385          0.01            46.0   
9991         2  38.245728 -122.625511          0.01            44.6   
9992         3  37.564606 -121.902275          0.01            43.0   
9993         3  38.744102 -121.270569          0.01            42.8   
9994         2  37.066490 -121

In [5]:
q.shape

NameError: name 'q' is not defined

In [54]:
tables=pd.crosstab(q['Severity'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 62.605 p_value 1.000


In [55]:
tables=pd.crosstab(q['Temperature(F)'],q['Humidity(%)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 104776.815 p_value 0.000


In [56]:
tables=pd.crosstab(q['Start_Lat'],q['Pressure(in)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 826500.786 p_value 0.000


In [57]:
tables=pd.crosstab(q['Humidity(%)'],q['Pressure(in)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 21727.217 p_value 0.000


In [58]:
tables=pd.crosstab(q['Severity'],q['Temperature(F)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 895.295 p_value 0.000


In [59]:
tables=pd.crosstab(q['Severity'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 62.605 p_value 1.000


In [60]:
tables=pd.crosstab(q['Wind_Chill(F)'],q['Distance(mi)'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 9957.961 p_value 0.000


In [61]:
tables=pd.crosstab(q['Start_Lat'],q['Start_Lng'])
from scipy.stats import chi2_contingency
chi2, p, dof, expected=chi2_contingency(tables.values)
print('Chi-square statistic %0.3f p_value %0.3f' %(chi2,p))

Chi-square statistic 61933932.540 p_value 0.000


In [12]:
pd.crosstab(q['Severity'],q['Distance(mi)'])

Distance(mi)  0.00   0.01   0.13   0.33   0.48   0.57   0.59   0.60   0.61   \
Severity                                                                      
1                 4      2      0      0      0      0      0      0      0   
2              2996   3029      1      1      1      0      0      0      0   
3              1828   2087      0      0      0      1      1      1      1   
4                 4      2      0      0      0      0      0      0      0   

Distance(mi)  0.67   ...  5.15   7.07   7.78   8.25   9.86   10.88  11.93  \
Severity             ...                                                    
1                 0  ...      0      0      0      0      0      0      0   
2                 1  ...      1      0      1      1      1      0      1   
3                 0  ...      0      1      0      0      0      1      0   
4                 0  ...      0      0      0      0      0      0      0   

Distance(mi)  12.18  14.08  24.04  
Severity                           
1                 0      0      0  
2                 1      1      1  
3                 0      0      0  
4                 0      0      0  

[4 rows x 45 columns]

In [13]:
from scipy.stats import chi2_contingency

In [16]:
chi2_contingency(pd.crosstab(q['Severity'],q['Distance(mi)']))

(62.604833059065896,
 0.9999999556733775,
 132,
 array([[2.8992000e+00, 3.0720000e+00, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 2.4000000e-03, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         1.2000000e-03, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04, 6.0000000e-04, 6.0000000e-04, 6.0000000e-04,
         6.0000000e-04],
        [2.9219104e+03, 3.0960640e+03, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470000e-01, 6.0470000e-01, 6.0470000e-01,
         6.0470000e-01, 6.0470

In [23]:
pd.crosstab(df['Wind_Direction'],df['Weather_Condition'])

Weather_Condition  Clear  Drizzle  Fog  Haze  Heavy Rain  Light Drizzle  \
Wind_Direction                                                            
Calm                1022        0    8    38           3              0   
ENE                   86        0    0     0           2              0   
ESE                   91        0    1     9           2              0   
East                 123        1    0    11           1              1   
NE                    82        0    0     0           1              0   
NNE                   87        0    0     4           0              0   
NNW                  387        0    1     3           0              0   
NW                   457        0    0     4           0              0   
North                288        0    1     2           0              0   
SE                   120        0    0     8           2              0   
SSE                  144        0    2     6           2              0   
SSW                  418        0    0     2           0              0   
SW                   325        0    0     3           0              2   
South                463        0    0    16           4              0   
Variable             194        0    0     2           0              0   
WNW                  542        0    0    12           0              0   
WSW                  181        0    0     4           0              0   
West                 485        0    2    10           1              0   

Weather_Condition  Light Freezing Drizzle  Light Freezing Fog  \
Wind_Direction                                                  
Calm                                    0                   0   
ENE                                     0                   0   
ESE                                     0                   0   
East                                    0                   0   
NE                                      0                   0   
NNE                                     0                   0   
NNW                                     0                   0   
NW                                      0                   0   
North                                   0                   0   
SE                                      6                   0   
SSE                                     2                   0   
SSW                                     2                   0   
SW                                      0                   0   
South                                   0                   2   
Variable                                0                   0   
WNW                                     0                   0   
WSW                                     0                   0   
West                                    0                   0   

Weather_Condition  Light Freezing Rain  Light Haze  ...  Mist  Mostly Cloudy  \
Wind_Direction                                      ...                        
Calm                                 0           0  ...     5            140   
ENE                                  0           0  ...     0             23   
ESE                                  0           0  ...     0             38   
East                                 0           0  ...     0             17   
NE                                   1           0  ...     0             15   
NNE                                  0           0  ...     0             16   
NNW                                  0           0  ...     2             24   
NW                                   0           0  ...     0             37   
North                                0           0  ...     0             18   
SE                                   0           1  ...     0             51   
SSE                                  0           0  ...     2             39   
SSW                                  0           0  ...     0             25   
SW                                   0           0  ...     2             24  

In [24]:
chi2_contingency(pd.crosstab(df['Wind_Direction'],df['Weather_Condition']))

(2296.1567270209725,
 5.528483547174103e-273,
 374,
 array([[9.27187783e+02, 1.68732991e-01, 2.53099486e+00, 2.26102207e+01,
         3.03719383e+00, 5.06198972e-01, 1.68732991e+00, 3.37465981e-01,
         1.68732991e-01, 1.68732991e-01, 1.14063502e+02, 1.68732991e-01,
         1.85606290e+01, 1.85606290e+00, 1.18113093e+02, 2.36732386e+02,
         1.29249471e+02, 3.37465981e-01, 1.88980950e+01, 7.54236468e+01,
         6.74931963e-01, 3.37465981e-01, 1.18113093e+00],
        [9.24972281e+01, 1.68329805e-02, 2.52494708e-01, 2.25561939e+00,
         3.02993650e-01, 5.04989416e-02, 1.68329805e-01, 3.36659611e-02,
         1.68329805e-02, 1.68329805e-02, 1.13790948e+01, 1.68329805e-02,
         1.85162786e+00, 1.85162786e-01, 1.17830864e+01, 2.36166717e+01,
         1.28940631e+01, 3.36659611e-02, 1.88529382e+00, 7.52434230e+00,
         6.73319222e-02, 3.36659611e-02, 1.17830864e-01],
        [1.48992541e+02, 2.71142022e-02, 4.06713033e-01, 3.63330309e+00,
         4.88055640e-01, 8.13

In [28]:
pd.crosstab(df['Wind_Direction'],df['State'])

State             CA  OH  WV
Wind_Direction              
Calm            1648  29   0
ENE              141  27   0
ESE              255  15   0
East             240  24   0
NE               121  44   0
NNE              155  24   0
NNW              544  27   0
NW               691  43   0
North            480  26   0
SE               365  39   0
SSE              478  40   0
SSW              533  71   0
SW               423  62   0
South            776  70   0
Variable         281   3   0
WNW              955  55   0
WSW              300  54   1
West             856  71   0

In [29]:
chi2_contingency(pd.crosstab(df['Wind_Direction'],df['State']))

(338.1637688462235,
 8.719374310272517e-52,
 34,
 array([[1.55501495e+03, 1.21816795e+02, 1.68255242e-01],
        [1.55779673e+02, 1.22034715e+01, 1.68556236e-02],
        [2.50360189e+02, 1.96127220e+01, 2.70893950e-02],
        [2.44796629e+02, 1.91768837e+01, 2.64874084e-02],
        [1.52997893e+02, 1.19855523e+01, 1.65546303e-02],
        [1.65979532e+02, 1.30025083e+01, 1.79592656e-02],
        [5.29465436e+02, 4.14772750e+01, 5.72890539e-02],
        [6.80608809e+02, 5.33175479e+01, 7.36430220e-02],
        [4.69193539e+02, 3.67556938e+01, 5.07675329e-02],
        [3.74613023e+02, 2.93464433e+01, 4.05337614e-02],
        [4.80320658e+02, 3.76273703e+01, 5.19715060e-02],
        [5.60065015e+02, 4.38743855e+01, 6.05999799e-02],
        [4.49721080e+02, 3.52302599e+01, 4.86605799e-02],
        [7.84461924e+02, 6.14531955e+01, 8.48801043e-02],
        [2.63341828e+02, 2.06296779e+01, 2.84940303e-02],
        [9.36532557e+02, 7.33661082e+01, 1.01334404e-01],
        [3.29177285e+02

In [32]:
pd.crosstab(df['Timezone'],df['State'])

State         CA   OH  WV
Timezone                 
US/Eastern     0  726   2
US/Pacific  9271    0   0

In [33]:
chi2_contingency(pd.crosstab(df['Timezone'],df['State']))

(9999.0, 0.0, 2, array([[6.74996300e+02, 5.28580858e+01, 1.45614561e-01],
        [8.59600370e+03, 6.73141914e+02, 1.85438544e+00]]))

In [34]:
chi2_contingency(pd.crosstab(df['Sunrise_Sunset'],df['State']))

(44.275330206153605,
 2.4307159093495694e-10,
 2,
 array([[5.5919432e+03, 4.3785060e+02, 1.2062000e+00],
        [3.6800568e+03, 2.8814940e+02, 7.9380000e-01]]))

In [35]:
chi2_contingency(pd.crosstab(df['Civil_Twilight'],df['State']))

(90.73510544928801,
 1.9820846318771448e-20,
 2,
 array([[5.9554056e+03, 4.6630980e+02, 1.2846000e+00],
        [3.3165944e+03, 2.5969020e+02, 7.1540000e-01]]))

In [36]:
chi2_contingency(pd.crosstab(df['Nautical_Twilight'],df['State']))

(146.36659462237992,
 1.647774623614261e-32,
 2,
 array([[6.2502552e+03, 4.8939660e+02, 1.3482000e+00],
        [3.0217448e+03, 2.3660340e+02, 6.5180000e-01]]))

In [37]:
chi2_contingency(pd.crosstab(df['Astronomical_Twilight'],df['State']))

(157.09257064087984,
 7.72292311609932e-35,
 2,
 array([[6.6378248e+03, 5.1974340e+02, 1.4318000e+00],
        [2.6341752e+03, 2.0625660e+02, 5.6820000e-01]]))

In [38]:
chi2_contingency(pd.crosstab(df['Civil_Twilight'],df['Street']))

(2430.327967168202,
 0.02531022509359213,
 2296,
 array([[1.2846, 0.6423, 0.6423, ..., 1.2846, 1.2846, 0.6423],
        [0.7154, 0.3577, 0.3577, ..., 0.7154, 0.7154, 0.3577]]))

In [40]:
pd.crosstab(df['Astronomical_Twilight'],df['Street'])

Street                 10th St  13th St  15th Ave  15th St  164th Ave  \
Astronomical_Twilight                                                   
Day                          1        0         1        1          0   
Night                        1        1         0        0          1   

Street                 165th Ave  16th St  17th Ave  17th St  19th Ave  ...  \
Astronomical_Twilight                                                   ...   
Day                            1        6         2        2         1  ...   
Night                          1        0         1        2         0  ...   

Street                 Wyda Way  Wyoming St  X Street Broadway Aly  \
Astronomical_Twilight                                                
Day                           0           2                      1   
Night                         1           0                      0   

Street                 Yerba Buena Rd  Yolo Ave  Yosemite Blvd  Zangol Pl  \
Astronomical_Twilight                                                       
Day                                 2         1              1          1   
Night                               3         0              3          0   

Street                 Zinfandel Dr  Zinfandel Ln  Zygmunt Dr  
Astronomical_Twilight                                          
Day                               1             2           1  
Night                             1             0           0  

[2 rows x 2297 columns]

In [41]:
chi2_contingency(pd.crosstab(df['Astronomical_Twilight'],df['Street']))

(2402.345907686875,
 0.05990691041468629,
 2296,
 array([[1.4318, 0.7159, 0.7159, ..., 1.4318, 1.4318, 0.7159],
        [0.5682, 0.2841, 0.2841, ..., 0.5682, 0.5682, 0.2841]]))

In [42]:
pd.crosstab(df['Nautical_Twilight'],df['Street'])

Street             10th St  13th St  15th Ave  15th St  164th Ave  165th Ave  \
Nautical_Twilight                                                              
Day                      1        0         1        1          0          1   
Night                    1        1         0        0          1          1   

Street             16th St  17th Ave  17th St  19th Ave  ...  Wyda Way  \
Nautical_Twilight                                        ...             
Day                      5         2        2         1  ...         0   
Night                    1         1        2         0  ...         1   

Street             Wyoming St  X Street Broadway Aly  Yerba Buena Rd  \
Nautical_Twilight                                                      
Day                         2                      1               1   
Night                       0                      0               4   

Street             Yolo Ave  Yosemite Blvd  Zangol Pl  Zinfandel Dr  \
Nautical_Twilight                                                     
Day                       1              1          1             1   
Night                     0              3          0             1   

Street             Zinfandel Ln  Zygmunt Dr  
Nautical_Twilight                            
Day                           2           1  
Night                         0           0  

[2 rows x 2297 columns]

In [43]:
chi2_contingency(pd.crosstab(df['Nautical_Twilight'],df['Street']))

(2440.9383887075387,
 0.01763565681955304,
 2296,
 array([[1.3482, 0.6741, 0.6741, ..., 1.3482, 1.3482, 0.6741],
        [0.6518, 0.3259, 0.3259, ..., 0.6518, 0.6518, 0.3259]]))